tasks:
  - name: Environment Setup
    init: |
      echo "Running environment setup..."
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/gitpod/backend/java/1.8/gitpod-setup.sh
      #chmod 0755 database-setup.sh
      #bash database-setup.sh
      mvn clean install -q 2>&1
      if [ "$?" -ne "0" ]; then
        error_message="Server%20Start%20Failed:%20Exit%20Code%20$?"
        curl -X POST -d "message=$error_message" https://reqres.in/api/users
        exit $?
      fi
      res=$(curl -X POST -d "message=Environment%20Setup%20Started" https://reqres.in/api/users)
      echo "API Response: $response"
    command: echo "Environment setup completed"

  - name: Start Server
    init: |
      echo "Starting the server..."
    command: echo "Server started"
ports:
  - port: 8080
    name: "Backend Server"
    onOpen: open-browser
    visibility: public
  - port: 3306
    name: "MySQL Server"
    onOpen: ignore
    visibility: public
  - port: 27017
    name: "MongoDB Server"
    onOpen: ignore
    visibility: public
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - gabrielbb.vscode-lombok
