tasks:
    - name: Environment Setup
    init: |
      echo "Running environment setup..."
      ./post_to_api.sh "Environment%20Setup%20Started"
      # Put your actual environment setup commands here
      . $HOME/.nvm/nvm.sh
      nvm install <node_version>
    command: echo "Environment setup completed"

  - name: Start Server
    init: |
      echo "Starting the server..."
      ./post_to_api.sh "Server%20Start%20Requested"
      # Put your actual server start commands here
      npm start
    command: echo "Server started"
ports:
  - port: 8080
    name: "Backend Server"
    onOpen: open-browser
    visibility: public
  - port: 3306
    name: "MySQL Server"
    onOpen: ignore
    visibility: public
  - port: 27017
    name: "MongoDB Server"
    onOpen: ignore
    visibility: public
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - gabrielbb.vscode-lombok
